### ISSUE TITLE
Poweroff issue

### ISSUE THREAD

**Issue by tolikes** [edwin170/downr1n#130]
[issue.zip](https://github.com/user-attachments/files/17417069/issue.zip)

There is a problem I don't know how to describe it correctly, in short the downgrade to ios 13.7 iphone 7 plus was completed successfully after that the device turned off and I couldn't turn it on, I have even held down the volume down button and the power button for more than 3 minutes and the phone doesn't react at all.

**Comment by edwin170** [comment]
> [issue.zip](https://github.com/user-attachments/files/17417069/issue.zip)
> 
> There is a problem I don't know how to describe it correctly, in short the downgrade to ios 13.7 iphone 7 plus was completed successfully after that the device turned off and I couldn't turn it on, I have even held down the volume down button and the power button for more than 3 minutes and the phone doesn't react at all.

because it's a tethered downgrade, you must --boot with downr1n to boot it up, remember first it will be in false dfu mode.

do this to put it in the correct mode:
First: execute sudo ./binaries/$(uname)/gaster pwn, if that start to loop (like never finish) Force reboot when the loop stop please press home button (or volume down) and stop gaster by pressing ctrl + c in your computer and after 10 second execute the command again

**Comment by tolikes** [comment]
Thanks, everything is fine, I had a kernel panic in my heart and I was thinking of removing the screen and turning off the power to the motherboard battery :D
